### ISSUE TITLE
crashed when using /sort

### ISSUE THREAD

**Issue by BennyNTHU** [liao2000/Music-Start-Discord-Bot-Pro#1]
When I try to use /sort, Music Start Pro crashed 
it stopped playing music and refuse to respond to any command like this

![image](https://user-images.githubusercontent.com/87105474/163457598-bd2a1bfa-5ca5-45a1-9a6a-5c2a9554e3d0.png)

so I kick it out and try attaching again, but it's still no response

**Comment by liao2000** [comment]
![1644433887632.jpg](https://user-images.githubusercontent.com/13825170/163505433-98c7561a-a99c-43fd-b729-8c6ab8501cd3.jpg)

The program is halted which is caused by other dependencies, maybe discord.js or ytdl-core. I will try to use a database to record all states at runtime, and recover through the database when error occurs.
